# Generated by Django 4.0.6 on 2022-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Khasara', models.IntegerField()),
                ('Advisoryname', models.CharField(max_length=200)),
            ],
        ),
    ]
