# Generated by Django 4.0.6 on 2022-07-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_author_booking_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Author',
            new_name='author',
        ),
    ]
